@extends('layout')
@section('title','Checkout')
@section('content')
<div class="page-heading"><span class="eyebrow">ONE LAST STEP</span><h1>Let’s make it yours.</h1><p class="muted">1. Your details <span>→</span> 2. PayMongo checkout <span>→</span> 3. Order confirmation</p></div>
@if(!$payReady)<div class="notice">PayMongo test checkout is awaiting configuration. You can review your order below. Your cart stays saved.</div>@endif
<form action="{{ route('checkout.place') }}" method="post" id="checkout-form" class="checkout-grid">@csrf<div class="panel stack"><h2>Contact & delivery</h2><div class="two-col"><label>Recipient name<input name="recipient" required maxlength="100" value="{{ old('recipient',auth()->user()->name) }}" autocomplete="name"></label><label>Mobile number<input name="phone" type="tel" required pattern="\+?[0-9]{10,15}" placeholder="09xxxxxxxxx" value="{{ old('phone') }}" autocomplete="tel"></label></div>
<label>How would you like your order?<select id="delivery-method" name="delivery_method"><option value="pickup" @selected(old('delivery_method')==='pickup')>Store pickup · Free</option><option value="lalamove" @selected(old('delivery_method')==='lalamove') @disabled(!$deliveryReady)>Lalamove {{ config('shop.lalamove.mode')==='sandbox'?'sandbox':'' }} delivery{{ !$deliveryReady?' · Not configured':'' }}</option></select></label>
<label>Address / pickup note<textarea name="address" id="delivery-address" required maxlength="500" rows="3" placeholder="For pickup, enter a note for store staff. For delivery, enter your complete address.">{{ old('address') }}</textarea></label>
<div id="delivery-fields" hidden><p class="muted">Enter the exact delivery coordinates to request a Lalamove quote.</p><div class="two-col"><label>Latitude<input id="delivery-lat" name="lat" type="number" step="any" min="-90" max="90" value="{{ old('lat') }}"></label><label>Longitude<input id="delivery-lng" name="lng" type="number" step="any" min="-180" max="180" value="{{ old('lng') }}"></label></div><button type="button" id="quote-button" class="button" data-url="{{ route('checkout.quote') }}">Get delivery quote ↗</button><p id="quote-result" role="status"></p></div>
<div class="mini-note">Your payment is entered on PayMongo’s checkout page. Zone One Tee’s does not collect card details.</div></div>
<aside class="panel order-summary"><span class="eyebrow">ORDER SUMMARY</span><h2>{{ $summary['quantity'] }} good choices.</h2><div class="pricing-badge">{{ $summary['label'] }} pricing</div><dl><div><dt>Clothing</dt><dd>₱{{ number_format($summary['base']/100,2) }}</dd></div>@if($summary['discount'])<div class="saving"><dt>Bulk · 5% discount</dt><dd>−₱{{ number_format($summary['discount']/100,2) }}</dd></div>@endif<div><dt>Delivery</dt><dd id="shipping-value">Free pickup</dd></div><div class="total"><dt>Total</dt><dd id="checkout-total" data-subtotal="{{ $summary['subtotal'] }}">₱{{ number_format($summary['subtotal']/100,2) }}</dd></div></dl><button id="pay-button" class="button dark" @disabled(!$payReady)>Continue to PayMongo →</button><small>{{ config('shop.paymongo.mode')==='test'?'Test payment · No real money is charged.':'Secure hosted payment.' }}</small><a class="text-link" href="{{ route('cart') }}">← Return to cart</a></aside></form>
@endsection