@extends('layout')
@section('content')
@if(!request()->hasAny(['q','category','wishlist','size','color','in_stock']))
<section class="hero"><div class="hero-copy"><span class="eyebrow"><span class="dot"></span> YOUR EVERYDAY, UPGRADED</span><h1>Good tees.<br>Better everyday.</h1><p>Comfort you’ll reach for. Prices you’ll love.<br>Find your next favorite, one tee at a time.</p><a class="button dark" href="#catalog">Explore the collection <span>↗</span></a><div class="hero-foot">ESSENTIALS FOR EVERYONE <span>01 — 08</span></div></div>
<div class="hero-art"><div class="hero-circle"></div><div class="hero-shirt one"><x-shirt color="#c8b59c"/></div><div class="hero-shirt two"><x-shirt color="#621708"/></div><span class="hero-sticker">EVERYDAY<br>ESSENTIALS<small>ZONE ONE TEE’S</small></span><span class="hero-caption">A little comfort goes a long way.</span></div></section>
<div class="benefits"><div><span>◇</span><b>Find your perfect fit<small>Sizes and colors for your everyday</small></b></div><div><span>↘</span><b>More pieces, more savings<small>Quantity pricing applied automatically</small></b></div><div><span>▣</span><b>Pay with confidence<small>Hosted checkout through PayMongo</small></b></div><div><span>✧</span><b>A little help, anytime<small>Ask our store assistant</small></b></div></div>
@endif
<section id="catalog"><div class="section-heading"><div><span class="eyebrow">THE EVERYDAY EDIT</span><h2>{{ request('wishlist')?'Your wishlist':(request('q')?'Results for “'.request('q').'”':'Find your next favorite') }}</h2></div><span class="muted">{{ $products->count() }} styles to explore</span></div>
<form class="filters" action="{{ route('store') }}">
@if(request('wishlist'))<input type="hidden" name="wishlist" value="1">@endif
<label><span class="sr-only">Search catalog</span><input name="q" placeholder="Search products…" value="{{ request('q') }}"></label>
<label><span class="sr-only">Category</span><select name="category"><option value="">All collections</option>@foreach($categories as $category)<option @selected(request('category')===$category)>{{ $category }}</option>@endforeach</select></label>
<label><span class="sr-only">Size</span><select name="size"><option value="">All sizes</option>@foreach(['S','M','L','XL','2XL'] as $size)<option @selected(request('size')===$size)>{{ $size }}</option>@endforeach</select></label>
<label><span class="sr-only">Color</span><select name="color"><option value="">All colors</option>@foreach(['Black','Ivory','Sage'] as $color)<option @selected(request('color')===$color)>{{ $color }}</option>@endforeach</select></label>
<label><span class="sr-only">Sort</span><select name="sort"><option value="">Featured</option><option value="price_asc" @selected(request('sort')==='price_asc')>Price: low to high</option><option value="price_desc" @selected(request('sort')==='price_desc')>Price: high to low</option></select></label>
<label class="check"><input type="checkbox" name="in_stock" value="1" @checked(request('in_stock'))> In stock</label><button class="button small">Apply</button><a class="text-link" href="{{ route('store') }}">Reset</a></form>
<div class="product-grid">@forelse($products as $product)
<article class="product-card"><div class="product-art" style="--art-bg:{{ $loop->iteration%2?'#fff8f2':'#fff4e7' }}"><a href="{{ route('product',$product) }}" aria-label="View {{ $product->name }}">@if($product->image_url)<img src="{{ $product->image_url }}" alt="{{ $product->name }}" loading="lazy">@else<x-shirt :color="$product->art_color" :polo="$product->category==='Polos'"/>@endif</a><span class="product-tag">{{ $product->category }}</span>
<form method="post" action="{{ route('wishlist.toggle',$product) }}">@csrf<button class="wish-button" aria-label="{{ in_array($product->id,$wishIds)?'Remove from':'Add to' }} wishlist">{{ in_array($product->id,$wishIds)?'♥':'♡' }}</button></form><span class="art-caption">{{ $product->image_url?'':'CATALOG ILLUSTRATION' }}</span></div>
<div class="product-meta"><div><span class="muted">{{ $product->category }}</span><a href="{{ route('product',$product) }}"><h3>{{ $product->name }}</h3></a></div><span class="product-arrow">↗</span></div>
<div class="product-bottom"><b>₱{{ number_format(($product->variants->min('retail_price')??0)/100,2) }}<small> / piece · SRP from</small></b><span class="swatches"><i style="background:#282a29"></i><i style="background:#e3d9c7"></i><i style="background:#8c9d8e"></i></span></div></article>
@empty<div class="empty-state"><h3>No products found</h3><p>Try another search or add a style to your wishlist.</p><a class="button" href="{{ route('store') }}">Browse all products</a></div>@endforelse</div></section>
<section id="quantity" class="quantity-section"><div><span class="eyebrow">GOOD VALUE, EVERY SIZE OF ORDER</span><h2>A few for you.<br>A lot for your crew.</h2><p>Your total clothing quantity determines the price.<br>Mix products, sizes, and colors in one order.</p></div><div class="tier-grid"><div><small>01 — 05 PIECES</small><h3>Retail</h3><p>Store owner’s SRP</p></div><div><small>06 — 50 PIECES</small><h3>Wholesale</h3><p>Store owner’s wholesale price</p></div><div><small>51 — 100 PIECES</small><h3>Re-seller</h3><p>Store owner’s re-seller price</p></div><div class="bulk-tier"><small>101+ PIECES</small><h3>Bulk · 5% off</h3><p>5% off the {{ config('shop.bulk_base','reseller')==='reseller'?'re-seller':config('shop.bulk_base','reseller') }} clothing subtotal</p></div></div></section>
@endsection