@extends('layout')
@section('title','Store overview')
@section('content')
<div class="section-heading"><div><span class="eyebrow">YOUR STORE, AT A GLANCE</span><h1>Welcome back, {{ explode(' ',auth()->user()->name)[0] }} <span class="hello-dot">✳</span></h1><p class="muted">Here’s what’s happening at Zone One Tee’s.</p></div><a class="button" href="{{ route('admin.reports.export') }}">↓ Export sales</a></div>
<div class="stat-grid"><article class="panel stat"><span>Clothing revenue <i>↗</i></span><h2>₱{{ number_format($revenue/100,2) }}</h2><small>All verified paid orders · excludes delivery</small></article><article class="panel stat"><span>Paid orders <i>▤</i></span><h2>{{ number_format($ordersCount) }}</h2><small>{{ $toPack }} waiting to be packed</small></article><article class="panel stat"><span>Customers <i>♧</i></span><h2>{{ number_format($customers) }}</h2><small>Registered customer accounts</small></article><article class="panel stat"><span>Average order value <i>◇</i></span><h2>₱{{ number_format($ordersCount?$revenue/$ordersCount/100:0,2) }}</h2><small>Clothing revenue / paid orders</small></article></div>
<div class="dashboard-grid" id="reports"><section class="panel"><div class="section-heading"><h3>Revenue over time</h3><span class="badge">Last 7 days</span></div><p class="muted">Confirmed clothing sales in Philippine pesos</p><div class="revenue-chart" aria-label="Revenue by day">@php($max=max(1,max(array_column($chart,'amount'))))@foreach($chart as $day)<div class="chart-column"><span>₱{{ number_format($day['amount']/100,0) }}</span><div class="bar-track"><div class="chart-bar" style="height:{{ $day['amount']/$max*100 }}%"></div></div><small>{{ $day['label'] }}</small></div>@endforeach</div>@if(!$ordersCount)<p class="empty-note">Your first verified payment will start your sales chart.</p>@endif</section>
<section class="panel"><div class="section-heading"><h3>Best sellers</h3><span class="muted">Units sold</span></div>@forelse($best as $name=>$units)<div class="rank-row"><span class="rank">{{ $loop->iteration }}</span><b>{{ $name }}</b><span>{{ $units }} pcs</span></div>@empty<div class="small-empty"><span>◇</span><h3>Ready for your first sale</h3><p>Best sellers will appear after verified payments.</p></div>@endforelse</section></div>
<div class="dashboard-grid"><section class="panel"><div class="section-heading"><h3>Recent orders</h3><a class="text-link" href="{{ route('admin.orders') }}">View all →</a></div><div class="table-scroll"><table><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody>@forelse($recent as $order)<tr><td><a class="text-link" href="{{ route('orders.show',$order) }}">{{ $order->number }}</a></td><td>{{ $order->user->name }}</td><td>₱{{ number_format($order->total/100,2) }}</td><td><span class="badge">{{ str_replace('_',' ',$order->status) }}</span></td></tr>@empty<tr><td colspan="4" class="empty-note">Orders will appear here as customers check out.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><div class="section-heading"><h3>Inventory attention</h3><span class="badge">Available stock</span></div>@forelse($lowStock as $v)<div class="rank-row"><b>{{ $v->product->name }}<small>{{ $v->size }} / {{ $v->color }}</small></b><span class="badge warning">{{ $v->available() }} left</span></div>@empty<div class="small-empty"><span>✓</span><h3>All stocked up</h3><p>No variants are below their reorder threshold.</p></div>@endforelse</section></div>
<section class="panel category-report"><h3>Sales by category</h3>@forelse($category as $name=>$amount)<div class="category-row"><b>{{ $name }}</b><div><i style="width:{{ $amount/max(1,$revenue)*100 }}%"></i></div><span>₱{{ number_format($amount/100,2) }}</span></div>@empty<p class="muted">Category breakdown will appear after verified sales.</p>@endforelse</section>
<section class="panel forecast-panel" id="forecast"><div class="section-heading"><div><span class="eyebrow">PLAN AHEAD</span><h2>Sales & growth forecast</h2></div><span class="badge">For {{ $revenueForecast['target'] }}</span></div>
<p class="muted">Uses up to 6 completed calendar months. This month is forecast from the completed months, so partial sales do not distort the estimate. Historical growth needs 2 months with a nonzero earlier month; regression needs 3 completed months. Estimates are not guarantees.</p>
<div class="two-col forecast-methods"><div class="method-card"><span class="eyebrow">HISTORICAL GROWTH</span><h3>Previous period sales × (1 + growth rate)</h3><p>Growth rate = (last completed month − month before) / month before.</p><h2>{{ $revenueForecast['growth']['prediction']===null?'Needs sales history':'₱'.number_format($revenueForecast['growth']['prediction']/100,2) }}</h2><small>Revenue forecast · Rate {{ $revenueForecast['growth']['rate']===null?'unavailable':number_format($revenueForecast['growth']['rate']*100,2).'%' }}</small></div>
<div class="method-card"><span class="eyebrow">LINEAR REGRESSION</span><h3>y = a + bx</h3><p>y = clothing revenue; x = chronological month number; a = intercept; b = change per month.</p><h2>{{ $revenueForecast['regression']['prediction']===null?'Needs sales history':'₱'.number_format($revenueForecast['regression']['prediction']/100,2) }}</h2><small>a: {{ $revenueForecast['regression']['a']===null?'—':'₱'.number_format($revenueForecast['regression']['a']/100,2) }} · b: {{ $revenueForecast['regression']['b']===null?'—':'₱'.number_format($revenueForecast['regression']['b']/100,2) }} · target x: {{ count($revenueForecast['months'])+1 }}</small></div></div>
<details class="forecast-details"><summary>View historical periods and calculation inputs</summary><div class="table-scroll"><table><thead><tr><th>x</th><th>Period</th><th>Net clothing revenue (y)</th></tr></thead><tbody>@forelse($revenueForecast['months'] as $i=>$month)<tr><td>{{ $i+1 }}</td><td>{{ $month }}</td><td>₱{{ number_format($revenueForecast['values'][$i]/100,2) }}</td></tr>@empty<tr><td colspan="3">No completed months of paid orders yet.</td></tr>@endforelse</tbody></table></div></details>
<h3>Product demand · pieces per month</h3><div class="table-scroll"><table><thead><tr><th>Product</th><th>Historical units</th><th>Growth forecast</th><th>Regression forecast</th><th>Available</th><th>Suggested reorder</th></tr></thead><tbody>@foreach($forecasts as $row)<tr><td>{{ $row['name'] }}<small>{{ $row['category'] }}</small></td><td>{{ $row['sold'] }}</td><td>{{ $row['growth']['prediction']===null?'Needs history':ceil($row['growth']['prediction']).' pcs' }}<small>{{ $row['growth']['rate']===null?'':number_format($row['growth']['rate']*100,1).'% growth' }}</small></td><td>{{ $row['forecast']===null?'Needs history':$row['forecast'].' pcs' }}</td><td>{{ $row['available'] }}</td><td>{{ $row['reorder']??'—' }}</td></tr>@endforeach</tbody></table></div>
<h3 style="margin-top:25px">Category demand · pieces per month</h3><div class="table-scroll"><table><thead><tr><th>Category</th><th>Growth forecast</th><th>Regression forecast</th><th>Intercept (a)</th><th>Slope (b)</th></tr></thead><tbody>@foreach($categoryForecast as $row)<tr><td>{{ $row['name'] }}</td><td>{{ $row['growth']['prediction']===null?'Needs history':ceil($row['growth']['prediction']) }}</td><td>{{ $row['regression']['prediction']===null?'Needs history':ceil($row['regression']['prediction']) }}</td><td>{{ $row['regression']['a']===null?'—':number_format($row['regression']['a'],2) }}</td><td>{{ $row['regression']['b']===null?'—':number_format($row['regression']['b'],2) }}</td></tr>@endforeach</tbody></table></div>
<p class="muted">Negative regression estimates display as zero demand. Reorder suggestions use the regression estimate minus available inventory. Delivery charges are excluded from forecast revenue.</p></section>
@endsection