@extends('layout')
@section('title','Store settings')
@section('crumb','Settings')
@section('content')
<div class="page-heading"><span class="eyebrow">CONNECTED, THOUGHTFULLY</span><h1>Store settings</h1><p class="muted">Connect services and give the assistant your store’s approved answers.</p></div>
<div class="three-col integration-cards"><div class="panel"><span class="eyebrow">PAYMENTS</span><h2>PayMongo</h2><span class="badge">{{ $payReady?'Configured · '.config('shop.paymongo.mode'):'Awaiting configuration' }}</span><p>Hosted checkout with verified payment notifications.</p><small>Set PAYMONGO_SECRET_KEY and PAYMONGO_WEBHOOK_SECRET in the local .env file. The webhook URL must be reachable by PayMongo.</small><p><a class="text-link" href="https://docs.paymongo.com/docs/payment-channels-hosted-checkout" target="_blank" rel="noopener">Setup documentation ↗</a></p></div>
<div class="panel"><span class="eyebrow">DELIVERY</span><h2>Lalamove</h2><span class="badge">{{ $deliveryReady?'Configured · '.config('shop.lalamove.mode'):'Awaiting configuration' }}</span><p>Address-based quotes, staff booking, and delivery status updates.</p><small>Set LALAMOVE_API_KEY, LALAMOVE_API_SECRET, and the STORE_PICKUP values in .env. Start with sandbox credentials.</small><p><a class="text-link" href="https://developers.lalamove.com/" target="_blank" rel="noopener">Setup documentation ↗</a></p></div>
<div class="panel"><span class="eyebrow">ASSISTANCE</span><h2>Grok</h2><span class="badge">{{ $grokReady?'Configured':'Basic help active' }}</span><p>Separate customer and staff contexts. Customers only access their own orders.</p><small>Set GROK_API_KEY and an available GROK_MODEL in .env. Configure the store’s approved answers below.</small><p><a class="text-link" href="https://docs.x.ai/developers/rest-api-reference/inference" target="_blank" rel="noopener">Setup documentation ↗</a></p></div></div>
<form class="panel stack" method="post" action="{{ route('admin.settings.save') }}">@csrf<h2>Chatbot store guidance</h2><p class="muted">Add approved opening hours, sizing measurements, pickup instructions, return policy, and support contact details. Do not include private customer data or API keys.</p><label>Approved FAQs and store information<textarea name="faq" rows="10" maxlength="5000">{{ old('faq',$faq) }}</textarea></label><button class="button dark">Save store guidance</button></form>
@endsection